USE master

ALTER DATABASE DiabetesUnitsManager
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE DiabetesUnitsManager
GO

CREATE DATABASE DiabetesUnitsManager
GO

USE DiabetesUnitsManager

CREATE TABLE [dbo].[INVENTORY] (
	[INVENTORYID] [uniqueidentifier] NOT NULL
		CONSTRAINT PK_INVENTORY PRIMARY KEY,
	[KEY] [nvarchar](64) NOT NULL,
	[DEFAULT_TYPE] [nvarchar](80) NULL,
	[USERID] [uniqueidentifier] NOT NULL,
	[HASH] [nvarchar](2000) NOT NULL,
	[CREATED] [DATETIMEOFFSET](7) NOT NULL,
	[MODIFIED] [DATETIMEOFFSET](7) NULL,
	CONSTRAINT UQ_INVENTORY UNIQUE ([KEY], [DEFAULT_TYPE], [USERID]),
	INDEX IX_INVENTORY NONCLUSTERED ([KEY], [USERID])
)


CREATE TABLE [dbo].[INVENTORY_HISTORY] (
	[INVENTORY_HISTORYID] [uniqueidentifier] NOT NULL
		CONSTRAINT PK_INVENTORY_HISTORY PRIMARY KEY,
	[INVENTORYID] [uniqueidentifier] NOT NULL
		CONSTRAINT FK_INVENTORY_HISTORY_INVENTORY
		REFERENCES [dbo].[INVENTORY],
	[VERSION] [int] NOT NULL,
	[TYPE] [nvarchar](80) NOT NULL,
	[ITEMS] [nvarchar](max) NOT NULL,
	[HASH] [nvarchar](2000) NOT NULL,
	[CREATED] [DATETIMEOFFSET](7) NOT NULL,
	CONSTRAINT UQ_INVENTORY_HISTORY UNIQUE ([INVENTORYID], [VERSION], [TYPE]),
	INDEX IX_INVENTORY_HISTORY NONCLUSTERED ([INVENTORYID], [VERSION], [TYPE])
) 


CREATE TABLE [dbo].[USER] (
	[USERID] [uniqueidentifier] NOT NULL
		CONSTRAINT PK_USER PRIMARY KEY,
	[EMAILADDRESS] [varchar](255) NULL
		CONSTRAINT UQ_USER UNIQUE,
	[USERNAME] [varchar](255) NULL
		CONSTRAINT UQ_USER_USERNAME UNIQUE,
	[HASH] [nvarchar](2000) NOT NULL,
	[CREATED] [DATETIMEOFFSET](7) NOT NULL,
	[MODIFIED] [DATETIMEOFFSET](7) NULL
)

ALTER TABLE [dbo].[INVENTORY]
    ADD CONSTRAINT FK_INVENTORY_USER 
        FOREIGN KEY ([USERID])
        REFERENCES [dbo].[USER]
GO

CREATE TABLE [dbo].[API_TOKEN] (
    [API_TOKENID] UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_API_TOKEN PRIMARY KEY,
    [KEY] NVARCHAR(200) NOT NULL
        CONSTRAINT UQ_API_TOKEN UNIQUE,
    [SECRET] NVARCHAR(MAX) NOT NULL,
    [CREATED] [DATETIMEOFFSET](7) NOT NULL
)

CREATE TABLE [dbo].[API_TOKEN_REQUEST] (
	[API_TOKEN_REQUESTID] UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_API_TOKEN_REQUEST PRIMARY KEY,
	[API_TOKENID] UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT FK_API_TOKEN_REQUEST
        REFERENCES [dbo].[API_TOKEN],
	[TOKEN] NVARCHAR(200) NOT NULL,
    [EXPIRES] [DATETIMEOFFSET](7) NOT NULL,
	[CREATED] [DATETIMEOFFSET](7) NOT NULL
	CONSTRAINT UQ_API_TOKEN_REQUEST UNIQUE ([TOKEN])
)

CREATE TABLE [dbo].[API_TOKEN_CLAIM] (
    [API_TOKEN_CLAIMID] UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_API_TOKEN_CLAIM PRIMARY KEY,
    [API_TOKENID] UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT FK_API_TOKEN_CLAIM
        REFERENCES [dbo].[API_TOKEN],
    [CLAIM] NVARCHAR(200) NOT NULL,
    [CREATED] [DATETIMEOFFSET](7) NOT NULL
)

select * FROM [INVENTORY_HISTORY]
ORDER BY CREATED DESC

SELECT  [INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], [INVENTORY_HISTORY].[Created],[INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY_HISTORY] INNER JOIN [dbo].[INVENTORY] ON [INVENTORY_HISTORY].[InventoryId] = [INVENTORY].[InventoryId] WHERE [INVENTORY_HISTORY].[INVENTORY_HISTORYID] = @InventoryHistoryId


Get: SELECT TOP(1) [User].[UserId], [User].[Username], [User].[EmailAddress], [User].[Hash], [User].[Created], [User].[Modified] FROM [dbo].[User] WHERE [User].[UserId] = @UserId
Get: SELECT TOP(1) [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY] WHERE [INVENTORY].[DEFAULT_TYPE] = @Type AND [INVENTORY].[Key] = @Key AND [INVENTORY].[UserId] = @UserId
Get: SELECT TOP(1) [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY] WHERE [INVENTORY].[InventoryId] = @InventoryId AND [INVENTORY].[Key] = @Key AND [INVENTORY].[UserId] = @UserId
Update: UPDATE [dbo].[INVENTORY] SET [INVENTORY].[DEFAULT_TYPE] = @DefaultType, [INVENTORY].[Modified] = @Modified WHERE [InventoryId]= @InventoryId
Get: SELECT TOP(1) [INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], [INVENTORY_HISTORY].[Created], [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY_HISTORY] INNER JOIN [dbo].[INVENTORY] ON [INVENTORY_HISTORY].[InventoryId] = [INVENTORY].[InventoryId] WHERE [INVENTORY_HISTORY].[InventoryId] = @InventoryId AND [INVENTORY_HISTORY].[Type] = @Type 
Insert: INSERT INTO [dbo].[INVENTORY_HISTORY] ([INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], [INVENTORY_HISTORY].[Created]) VALUES (@InventoryHistoryId, @InventoryId, @Version, @Type, @Items, @Hash, @Created); SELECT @InventoryHistoryId
Get: SELECT TOP(1) [INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], [INVENTORY_HISTORY].[Created], [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY_HISTORY] INNER JOIN [dbo].[INVENTORY] ON [INVENTORY_HISTORY].[InventoryId] = [INVENTORY].[InventoryId] WHERE [INVENTORY_HISTORY].[INVENTORY_HISTORYID] = @InventoryHistoryId 
Get: SELECT TOP(1) [User].[UserId], [User].[Username], [User].[EmailAddress], [User].[Hash], [User].[Created], [User].[Modified] FROM [dbo].[User] WHERE [User].[UserId] = @UserId
Get: SELECT TOP(1) [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY] WHERE [INVENTORY].[DEFAULT_TYPE] = @Type AND [INVENTORY].[Key] = @Key AND [INVENTORY].[UserId] = @UserId
Get: SELECT TOP(1) [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY] WHERE [INVENTORY].[InventoryId] = @InventoryId AND [INVENTORY].[Key] = @Key AND [INVENTORY].[UserId] = @UserId
Update: UPDATE [dbo].[INVENTORY] SET [INVENTORY].[DEFAULT_TYPE] = @DefaultType, [INVENTORY].[Modified] = @Modified WHERE [InventoryId]= @InventoryId
Get: SELECT TOP(1) [INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], [INVENTORY_HISTORY].[Created], [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY_HISTORY] INNER JOIN [dbo].[INVENTORY] ON [INVENTORY_HISTORY].[InventoryId] = [INVENTORY].[InventoryId] WHERE [INVENTORY_HISTORY].[InventoryId] = @InventoryId AND [INVENTORY_HISTORY].[Type] = @Type 
Insert: INSERT INTO [dbo].[INVENTORY_HISTORY] ([INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], [INVENTORY_HISTORY].[Created]) VALUES (@InventoryHistoryId, @InventoryId, @Version, @Type, @Items, @Hash, @Created); SELECT @InventoryHistoryId
Get: SELECT TOP(1) [INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], [INVENTORY_HISTORY].[Created], [INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] FROM [dbo].[INVENTORY_HISTORY] INNER JOIN [dbo].[INVENTORY] ON [INVENTORY_HISTORY].[InventoryId] = [INVENTORY].[InventoryId] WHERE [INVENTORY_HISTORY].[INVENTORY_HISTORYID] = @InventoryHistoryId 
The program '[24204] func.exe' has exited with code 4294967295 (0xffffffff).


DECLARE @Key NVARCHAR(200) = 'apples',
		@Type NVARCHAR(200) = 'bananas',
		@UserId UNIQUEIDENTIFIER = 'c55d2555-dc9a-4583-ada2-d68f9c21b184'

SELECT TOP(1) [INVENTORY_HISTORY].[INVENTORY_HISTORYID], [INVENTORY_HISTORY].[InventoryId], [INVENTORY_HISTORY].[Version], [INVENTORY_HISTORY].[Type], [INVENTORY_HISTORY].[Items], [INVENTORY_HISTORY].[Hash], 
[INVENTORY_HISTORY].[Created],[INVENTORY].[InventoryId], [INVENTORY].[UserId], [INVENTORY].[Key], [INVENTORY].[DEFAULT_TYPE], [INVENTORY].[Hash], [INVENTORY].[Created], [INVENTORY].[Modified] 
FROM [dbo].[INVENTORY_HISTORY] INNER JOIN [dbo].[INVENTORY] ON [INVENTORY_HISTORY].[InventoryId] = [INVENTORY].[InventoryId] 
WHERE [INVENTORY].[Key] = @Key AND [INVENTORY_HISTORY].[Type] = @Type AND [INVENTORY].[UserId] = @UserId